feat(Model): fetch tableName from (SSM) Parameter Store
neoxia/dynamodels pull request #291
Opened 2024-01-22 10:20 UTC by SajidHamza9

2024-01-23 10:38 UTC, MarioArnt requested changes
Althrough tableName became now a possible Promise, we do not need to change public API here.
It would need a major release and rewrite A LOT of tests.
Have a look on PR #288 , the implementation is non-breaking and test are passing.
Maybe you can merge both of PRs good ideas: decarator-style and defer-resolve table name in query and scan.

2024-01-23 10:38 UTC, MarioArnt commented on tsconfig.json
> +    "module": "ES2022",
We want to keep support of previous NodeJS versions, please revert to CommonJS

2024-01-23 10:38 UTC, MarioArnt commented on src/base-model.ts
> +  public async scan(options?: Partial<ScanCommandInput>): Promise<Scan<T>> {
For backward compatibility reason we do not want to change public API and make `scan` and `query` method async.

Solution here is to leave TableName empty and resolve it when async method `count`, `exec` or `execAll` are called.

2024-01-23 10:38 UTC, MarioArnt commented on src/base-model.ts
> +  protected tableName: string | Promise<string | undefined> | undefined;
Nice use case for a decorator 💯

2024-01-26 10:53 UTC, ThibaultRuby approved these changes

2024-01-30 09:01 UTC, MarioArnt requested changes
Well done !

Almost good for me 👍 

I'm just asking one more thing: 
Can you update README.md (first section) and mention this is now possible to load table name from SSM providing a code example.

2024-02-15 14:34 UTC, MarioArnt approved these changes

2024-02-15 14:35 UTC, merged

2024-02-15 14:38 UTC, MarioArnt commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/dynamodels/v/2.4.0)
- [GitHub release](https://github.com/neoxia/dynamodels/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: